# Generated by Django 4.2.2 on 2023-06-24 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_name', models.CharField(max_length=40)),
                ('p_address', models.CharField(max_length=30)),
                ('p_phone', models.CharField(max_length=17)),
            ],
        ),
    ]
